development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: simtekapp@gmail.com
  :password: simtekapp_password
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: simtekapp@gmail.com
  :password: simtekapp_password
  :enable_starttls_auto: true