development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: login
  :user_name: simtekapp@gmail.com
  :password: simtek_password
  :domain: google.com
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: login
  :user_name: simtekapp@gmail.com
  :password: simtek_password
  :domain: google.com
  :enable_starttls_auto: true