# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 042bd715931045ab93944812bd63b3ae88767c7961342b423ce6161b4ffbe885978ea0d17396f72d4f0b035ae88495d1a54696ebe34573abb405151a85d74f32

test:
  secret_key_base: f375a591f50f7446f8033b9d07e02ddd399d035bf554652f21222609bcacbde36362005fb890422e11388cfeded78d60dcc31e9d7901803b96b0d1994302925c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
